In [3]:
import pandas as pd
import numpy as np

In [4]:
excel_file = pd.ExcelFile("Adventure Sheet.xlsx")

In [5]:
excel_file.sheet_names

['Calendar',
 'Customers',
 'Products',
 'Territory',
 'Sales',
 'dimProductCategory',
 'dimProductSubCategory']

In [6]:
calendar = pd.read_excel(excel_file, sheet_name="Calendar")

In [7]:
calendar.head()

,ID,Date,DayNumberOfWeek,DayName,DayNumberOfMonth,DayNumberOfYear,WeekNumberOfYear,MonthName,MonthNumberOfYear,CalendarQuarter,CalendarYear,FiscalQuarter,FiscalYear,FiscalSemester,Period
0,1,2001-07-01,1,Sunday,1,182,27,July,7,3,2001,1,2002,1,200107
1,2,2001-07-02,2,Monday,2,183,27,July,7,3,2001,1,2002,1,200107
2,3,2001-07-03,3,Tuesday,3,184,27,July,7,3,2001,1,2002,1,200107
3,4,2001-07-04,4,Wednesday,4,185,27,July,7,3,2001,1,2002,1,200107
4,5,2001-07-05,5,Thursday,5,186,27,July,7,3,2001,1,2002,1,200107

In [8]:
calendar.info()

<class 'pandas.DataFrame'>
RangeIndex: 2560 entries, 0 to 2559
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 2560 non-null   int64
 1   Date               2560 non-null   datetime64[us]
 2   DayNumberOfWeek    2560 non-null   int64
 3   DayName            2560 non-null   str
 4   DayNumberOfMonth   2560 non-null   int64
 5   DayNumberOfYear    2560 non-null   int64
 6   WeekNumberOfYear   2560 non-null   int64
 7   MonthName          2560 non-null   str
 8   MonthNumberOfYear  2560 non-null   int64
 9   CalendarQuarter    2560 non-null   int64
 10  CalendarYear       2560 non-null   int64
 11  FiscalQuarter      2560 non-null   int64
 12  FiscalYear         2560 non-null   int64
 13  FiscalSemester     2560 non-null   int64
 14  Period             2560 non-null   int64
dtypes: datetime64[us](1), int64(12), str(2)
memory usage: 333.7 KB

In [9]:
calendar.describe(include="all")

,ID,Date,DayNumberOfWeek,DayName,DayNumberOfMonth,DayNumberOfYear,WeekNumberOfYear,MonthName,MonthNumberOfYear,CalendarQuarter,CalendarYear,FiscalQuarter,FiscalYear,FiscalSemester,Period
count,2560.000000,2560,2560.000000,2560,2560.000000,2560.000000,2560.000000,2560,2560.000000,2560.000000,2560.000000,2560.000000,2560.000000,2560.00000,2560.000000
unique,NaN,NaN,NaN,7,NaN,NaN,NaN,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,Sunday,NaN,NaN,NaN,July,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,366,NaN,NaN,NaN,248,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,640.500000,2003-04-01 12:00:00,3.997656,NaN,15.747656,196.152344,28.838281,NaN,6.949219,2.650781,2002.713281,2.350781,2003.288281,1.42500,200278.277344
min,1.000000,2001-07-01 00:00:00,1.000000,NaN,1.000000,1.000000,1.000000,NaN,1.000000,1.000000,2001.000000,1.000000,2002.000000,1.00000,200107.000000
25%,320.750000,2002-05-16 18:00:00,2.000000,NaN,8.000000,107.000000,16.000000,NaN,4.000000,2.000000,2002.000000,1.000000,2002.000000,1.00000,200205.000000
50%,640.500000,2003-04-01 12:00:00,4.000000,NaN,16.000000,206.000000,30.000000,NaN,7.000000,3.000000,2003.000000,2.000000,2003.000000,1.00000,200304.000000
75%,960.250000,2004-02-15 06:00:00,6.000000,NaN,23.000000,286.000000,42.000000,NaN,10.000000,4.000000,2004.000000,3.000000,2004.000000,2.00000,200402.000000
max,1280.000000,2004-12-31 00:00:00,7.000000,NaN,31.000000,366.000000,53.000000,NaN,12.000000,4.000000,2004.000000,4.000000,2005.000000,2.00000,200412.000000
std,369.576249,NaN,1.999412,NaN,8.810785,104.583789,14.915459,NaN,3.420475,1.107331,1.031650,1.108953,1.031214,0.49444,102.506243

In [10]:
calendar.isnull().sum()

ID                   0
Date                 0
DayNumberOfWeek      0
DayName              0
DayNumberOfMonth     0
DayNumberOfYear      0
WeekNumberOfYear     0
MonthName            0
MonthNumberOfYear    0
CalendarQuarter      0
CalendarYear         0
FiscalQuarter        0
FiscalYear           0
FiscalSemester       0
Period               0
dtype: int64

In [11]:
calendar.duplicated().sum()

np.int64(1280)

In [12]:
calendar.shape

(2560, 15)

In [13]:
calendar.tail()

,ID,Date,DayNumberOfWeek,DayName,DayNumberOfMonth,DayNumberOfYear,WeekNumberOfYear,MonthName,MonthNumberOfYear,CalendarQuarter,CalendarYear,FiscalQuarter,FiscalYear,FiscalSemester,Period
2555,1229,2004-11-10,4,Wednesday,10,315,46,November,11,4,2004,2,2005,1,200411
2556,1230,2004-11-11,5,Thursday,11,316,46,November,11,4,2004,2,2005,1,200411
2557,1231,2004-11-12,6,Friday,12,317,46,November,11,4,2004,2,2005,1,200411
2558,1232,2004-11-13,7,Saturday,13,318,46,November,11,4,2004,2,2005,1,200411
2559,1233,2004-11-14,1,Sunday,14,319,47,November,11,4,2004,2,2005,1,200411

In [14]:
calendar[calendar.duplicated()].head(10)

,ID,Date,DayNumberOfWeek,DayName,DayNumberOfMonth,DayNumberOfYear,WeekNumberOfYear,MonthName,MonthNumberOfYear,CalendarQuarter,CalendarYear,FiscalQuarter,FiscalYear,FiscalSemester,Period
1280,1,2001-07-01,1,Sunday,1,182,27,July,7,3,2001,1,2002,1,200107
1281,2,2001-07-02,2,Monday,2,183,27,July,7,3,2001,1,2002,1,200107
1282,3,2001-07-03,3,Tuesday,3,184,27,July,7,3,2001,1,2002,1,200107
1283,4,2001-07-04,4,Wednesday,4,185,27,July,7,3,2001,1,2002,1,200107
1284,5,2001-07-05,5,Thursday,5,186,27,July,7,3,2001,1,2002,1,200107
1285,6,2001-07-06,6,Friday,6,187,27,July,7,3,2001,1,2002,1,200107
1286,7,2001-07-07,7,Saturday,7,188,27,July,7,3,2001,1,2002,1,200107
1287,8,2001-07-08,1,Sunday,8,189,28,July,7,3,2001,1,2002,1,200107
1288,9,2001-07-09,2,Monday,9,190,28,July,7,3,2001,1,2002,1,200107
1289,10,2001-07-10,3,Tuesday,10,191,28,July,7,3,2001,1,2002,1,200107

In [15]:
calendar.drop_duplicates(inplace=True)

In [16]:
calendar.shape

(1280, 15)

In [17]:
calendar.duplicated().sum()

np.int64(0)

In [18]:
calendar["ID"].nunique()
calendar["Date"].nunique()

1280

In [19]:
calendar["Date"].duplicated().sum()
calendar["DayName"].value_counts()

DayName
Sunday       183
Monday       183
Tuesday      183
Wednesday    183
Thursday     183
Friday       183
Saturday     182
Name: count, dtype: int64

In [20]:
calendar["MonthName"].value_counts().sort_index()

MonthName
April         90
August       124
December     124
February      85
January       93
July         124
June          90
March         93
May           93
November     120
October      124
September    120
Name: count, dtype: int64

In [21]:
calendar["CalendarYear"].value_counts().sort_index()

CalendarYear
2001    184
2002    365
2003    365
2004    366
Name: count, dtype: int64

In [22]:
territory = pd.read_excel(excel_file, sheet_name="Territory")

In [23]:
territory.head()

   Territory Key     Region        Country          Group
0              1  Northwest  United States  North America
1              2  Northeast  United States  North America
2              3    Central  United States  North America
3              4  Southwest  United States  North America
4              5  Southeast  United States  North America

In [24]:
territory.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Territory Key  11 non-null     int64
 1   Region         10 non-null     str
 2   Country        10 non-null     str
 3   Group          10 non-null     str
dtypes: int64(1), str(3)
memory usage: 785.0 bytes

In [25]:
territory.describe(include="all")

        Territory Key     Region        Country          Group
count       11.000000         10             10             10
unique            NaN         10              6              3
top               NaN  Northwest  United States  North America
freq              NaN          1              5              6
mean         6.000000        NaN            NaN            NaN
std          3.316625        NaN            NaN            NaN
min          1.000000        NaN            NaN            NaN
25%          3.500000        NaN            NaN            NaN
50%          6.000000        NaN            NaN            NaN
75%          8.500000        NaN            NaN            NaN
max         11.000000        NaN            NaN            NaN

In [26]:
territory.isnull().sum()

Territory Key    0
Region           1
Country          1
Group            1
dtype: int64

In [27]:
territory.duplicated().sum()

np.int64(0)

In [28]:
territory[territory.isnull().any(axis=1)]

    Territory Key Region Country Group
10             11    NaN     NaN   NaN

In [29]:
territory["Territory Key"].nunique()

11

In [30]:
territory["Country"].value_counts(dropna=False)

Country
United States     5
Canada            1
France            1
Germany           1
Australia         1
United Kingdom    1
NaN               1
Name: count, dtype: int64

In [31]:
sales = pd.read_excel(excel_file, sheet_name="Sales")

In [32]:
sales["SalesTerritoryKey"].value_counts().sort_index()

SalesTerritoryKey
1      8993
2        27
3        20
4     12265
5        39
6      7620
7      5558
8      5625
9     13345
10     6906
Name: count, dtype: int64

In [33]:
territory.dropna(inplace=True)

In [34]:
territory.shape

(10, 4)

In [35]:
territory.isnull().sum()

Territory Key    0
Region           0
Country          0
Group            0
dtype: int64

In [36]:
categories = pd.read_excel(excel_file, sheet_name="dimProductCategory")

In [37]:
categories.head()

,ProductCategoryKey,ProductCategoryAlternateKey,EnglishProductCategoryName,SpanishProductCategoryName,FrenchProductCategoryName
0,1,1,Bikes,Bicicleta,Vélo
1,2,2,Components,Componente,Composant
2,3,3,Clothing,Prenda,Vêtements
3,4,4,Accessories,Accesorio,Accessoire
4,1,1,Bikes,Bicicleta,Vélo

In [38]:
categories.info()
categories.describe(include='all')
categories.isnull().sum()
categories.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ProductCategoryKey           8 non-null      int64
 1   ProductCategoryAlternateKey  8 non-null      int64
 2   EnglishProductCategoryName   8 non-null      str
 3   SpanishProductCategoryName   8 non-null      str
 4   FrenchProductCategoryName    8 non-null      str
dtypes: int64(2), str(3)
memory usage: 656.0 bytes

np.int64(4)

In [39]:
categories.shape

(8, 5)

In [40]:
categories.duplicated().sum()

np.int64(4)

In [41]:
categories.isnull().sum()

ProductCategoryKey             0
ProductCategoryAlternateKey    0
EnglishProductCategoryName     0
SpanishProductCategoryName     0
FrenchProductCategoryName      0
dtype: int64

In [42]:
categories["ProductCategoryKey"].nunique()

4

In [43]:
categories["EnglishProductCategoryName"].value_counts()

EnglishProductCategoryName
Bikes          2
Components     2
Clothing       2
Accessories    2
Name: count, dtype: int64

In [44]:
categories.drop_duplicates(inplace=True)

In [45]:
categories.shape

(4, 5)

In [46]:
categories.duplicated().sum()

np.int64(0)

In [47]:
subcategories = pd.read_excel(excel_file, sheet_name="dimProductSubCategory")

In [48]:
subcategories.head()

,ProductSubcategoryKey,ProductSubcategoryAlternateKey,EnglishProductSubcategoryName,SpanishProductSubcategoryName,FrenchProductSubcategoryName,ProductCategoryKey
0,1,1,Mountain Bikes,Bicicleta de montaña,VTT,1
1,2,2,Road Bikes,Bicicleta de carretera,Vélo de route,1
2,3,3,Touring Bikes,Bicicleta de paseo,Vélo de randonnée,1
3,4,4,Handlebars,Barra,Barre d'appui,2
4,5,5,Bottom Brackets,Eje de pedalier,Axe de pédalier,2

In [49]:
subcategories.info()

<class 'pandas.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 6 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ProductSubcategoryKey           74 non-null     int64
 1   ProductSubcategoryAlternateKey  74 non-null     int64
 2   EnglishProductSubcategoryName   74 non-null     str
 3   SpanishProductSubcategoryName   74 non-null     str
 4   FrenchProductSubcategoryName    74 non-null     str
 5   ProductCategoryKey              74 non-null     int64
dtypes: int64(3), str(3)
memory usage: 5.9 KB

In [50]:
subcategories.isnull().sum()

ProductSubcategoryKey             0
ProductSubcategoryAlternateKey    0
EnglishProductSubcategoryName     0
SpanishProductSubcategoryName     0
FrenchProductSubcategoryName      0
ProductCategoryKey                0
dtype: int64

In [51]:
subcategories.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
69     True
70     True
71     True
72     True
73     True
Length: 74, dtype: bool

In [52]:
subcategories.describe(include="all")

,ProductSubcategoryKey,ProductSubcategoryAlternateKey,EnglishProductSubcategoryName,SpanishProductSubcategoryName,FrenchProductSubcategoryName,ProductCategoryKey
count,74.00000,74.00000,74,74,74,74.000000
unique,NaN,NaN,37,37,37,NaN
top,NaN,NaN,Mountain Bikes,Bicicleta de montaña,VTT,NaN
freq,NaN,NaN,2,2,2,NaN
mean,19.00000,19.00000,NaN,NaN,NaN,2.783784
std,10.74996,10.74996,NaN,NaN,NaN,0.996848
min,1.00000,1.00000,NaN,NaN,NaN,1.000000
25%,10.00000,10.00000,NaN,NaN,NaN,2.000000
50%,19.00000,19.00000,NaN,NaN,NaN,3.000000
75%,28.00000,28.00000,NaN,NaN,NaN,4.000000
max,37.00000,37.00000,NaN,NaN,NaN,4.000000

In [53]:
subcategories.shape

(74, 6)

In [54]:
subcategories.duplicated().sum()

np.int64(37)

In [55]:
subcategories["ProductSubcategoryKey"].nunique()

37

In [56]:
subcategories[
    ~subcategories["ProductCategoryKey"].isin(
        categories["ProductCategoryKey"]
    )
]

Empty DataFrame
Columns: [ProductSubcategoryKey, ProductSubcategoryAlternateKey, EnglishProductSubcategoryName, SpanishProductSubcategoryName, FrenchProductSubcategoryName, ProductCategoryKey]
Index: []

In [57]:
subcategories.drop_duplicates(inplace=True)

In [58]:
subcategories.shape

(37, 6)

In [59]:
products = pd.read_excel(excel_file, sheet_name="Products")

In [60]:
products.head()

,ProductKey,ProductSubcategoryKey,ProductName,StandardCost,Color,SafetyStockLevel,ListPrice,Size,SizeRange,Weight,...,ProductLine,DealerPrice,Class,ModelName,Description,StartDate,EndDate,Status,SubCategory,Category
0,362,1,"Mountain-200 Black, 46",1105.8100,Black,100,2049.0982,46,42-46 CM,24.13,...,M,1229.4589,H,Mountain-200,Serious back-country riding. Perfect for all l...,2002-07-01,2003-06-30,NaN,Mountain Bikes,Bikes
1,363,1,"Mountain-200 Black, 46",1251.9813,Black,100,2294.9900,46,42-46 CM,24.13,...,M,1376.9940,H,Mountain-200,Serious back-country riding. Perfect for all l...,2003-07-01,NaT,Current,Mountain Bikes,Bikes
2,364,1,"Mountain-300 Black, 38",598.4354,Black,100,1079.9900,38,38-40 CM,25.35,...,M,647.9940,M,Mountain-300,For true trail addicts. An extremely durable ...,2002-07-01,2003-06-30,NaN,Mountain Bikes,Bikes
3,365,1,"Mountain-300 Black, 40",598.4354,Black,100,1079.9900,40,38-40 CM,25.77,...,M,647.9940,M,Mountain-300,For true trail addicts. An extremely durable ...,2002-07-01,2003-06-30,NaN,Mountain Bikes,Bikes
4,587,1,"Mountain-400-W Silver, 38",419.7784,Silver,100,769.4900,38,38-40 CM,26.35,...,M,461.6940,M,Mountain-400-W,This bike delivers a high-level of performance...,2003-07-01,NaT,Current,Mountain Bikes,Bikes

In [61]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ProductKey             397 non-null    int64
 1   ProductSubcategoryKey  397 non-null    int64
 2   ProductName            397 non-null    str
 3   StandardCost           395 non-null    float64
 4   Color                  341 non-null    str
 5   SafetyStockLevel       397 non-null    int64
 6   ListPrice              395 non-null    float64
 7   Size                   299 non-null    str
 8   SizeRange              299 non-null    str
 9   Weight                 275 non-null    float64
 10  DaysToManufacture      397 non-null    int64
 11  ProductLine            380 non-null    str
 12  DealerPrice            395 non-null    float64
 13  Class                  312 non-null    str
 14  ModelName              397 non-null    str
 15  Description            396 non-null    str
 16  StartDate              397 non-null    datetime64[us]
 17  EndDate                200 non-null    datetime64[us]
 18  Status                 197 non-null    str
 19  SubCategory            397 non-null    str
 20  Category               397 non-null    str
dtypes: datetime64[us](2), float64(4), int64(4), str(11)
memory usage: 138.9 KB

In [62]:
products.describe(include='all')

,ProductKey,ProductSubcategoryKey,ProductName,StandardCost,Color,SafetyStockLevel,ListPrice,Size,SizeRange,Weight,...,ProductLine,DealerPrice,Class,ModelName,Description,StartDate,EndDate,Status,SubCategory,Category
count,397.000000,397.000000,397,395.000000,341,397.000000,395.000000,299,299,275.000000,...,380,395.000000,312,397,396,397,200,197,397,397
unique,NaN,NaN,295,NaN,9,NaN,NaN,18,10,NaN,...,4,NaN,3,119,114,NaN,NaN,1,37,4
top,NaN,NaN,"HL Mountain Frame - Silver, 46",NaN,Black,NaN,NaN,44,42-46 CM,NaN,...,R,NaN,H,LL Road Frame,"The LL Frame provides a safe comfortable ride,...",NaN,NaN,Current,Road Frames,Components
freq,NaN,NaN,3,NaN,129,NaN,NaN,40,80,NaN,...,162,NaN,121,30,30,NaN,NaN,197,70,189
mean,408.000000,12.128463,NaN,434.265829,NaN,282.851385,747.661762,NaN,NaN,46.569055,...,NaN,448.597060,NaN,NaN,NaN,2002-10-14 13:47:00.151133,2003-02-18 14:24:00,NaN,NaN,NaN
min,210.000000,1.000000,NaN,0.856500,NaN,4.000000,2.290000,NaN,NaN,2.120000,...,NaN,1.374000,NaN,NaN,NaN,1998-06-01 00:00:00,2002-06-30 00:00:00,NaN,NaN,NaN
25%,309.000000,2.000000,NaN,37.120900,NaN,100.000000,69.990000,NaN,NaN,2.500000,...,NaN,41.994000,NaN,NaN,NaN,2002-07-01 00:00:00,2002-06-30 00:00:00,NaN,NaN,NaN
50%,408.000000,13.000000,NaN,204.625100,NaN,500.000000,364.090000,NaN,NaN,15.130000,...,NaN,218.454000,NaN,NaN,NaN,2002-07-01 00:00:00,2003-06-30 00:00:00,NaN,NaN,NaN
75%,507.000000,16.000000,NaN,660.914200,NaN,500.000000,1204.324800,NaN,NaN,23.770000,...,NaN,722.594900,NaN,NaN,NaN,2003-07-01 00:00:00,2003-06-30 00:00:00,NaN,NaN,NaN
max,606.000000,37.000000,NaN,2171.294200,NaN,500.000000,3578.270000,NaN,NaN,1050.000000,...,NaN,2146.962000,NaN,NaN,NaN,2003-07-01 00:00:00,2003-06-30 00:00:00,NaN,NaN,NaN
std,114.748275,9.423328,NaN,497.379884,NaN,220.417534,838.708451,NaN,NaN,147.796111,...,NaN,503.225071,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
products.isnull().sum()

ProductKey                 0
ProductSubcategoryKey      0
ProductName                0
StandardCost               2
Color                     56
SafetyStockLevel           0
ListPrice                  2
Size                      98
SizeRange                 98
Weight                   122
DaysToManufacture          0
ProductLine               17
DealerPrice                2
Class                     85
ModelName                  0
Description                1
StartDate                  0
EndDate                  197
Status                   200
SubCategory                0
Category                   0
dtype: int64

In [64]:
products.duplicated().sum()

np.int64(0)

In [65]:
products.shape

(397, 21)

In [66]:
products[["Status", "EndDate"]].head(20)

     Status    EndDate
0       NaN 2003-06-30
1   Current        NaT
2       NaN 2003-06-30
3       NaN 2003-06-30
4   Current        NaT
5   Current        NaT
6   Current        NaT
7   Current        NaT
8       NaN 2002-06-30
9       NaN 2002-06-30
10      NaN 2002-06-30
11      NaN 2002-06-30
12      NaN 2002-06-30
13      NaN 2002-06-30
14      NaN 2002-06-30
15      NaN 2002-06-30
16      NaN 2003-06-30
17  Current        NaT
18      NaN 2003-06-30
19  Current        NaT

In [67]:
products["ProductKey"].nunique()

397

In [68]:
products[
    ~products["ProductSubcategoryKey"].isin(
        subcategories["ProductSubcategoryKey"]
    )
]

Empty DataFrame
Columns: [ProductKey, ProductSubcategoryKey, ProductName, StandardCost, Color, SafetyStockLevel, ListPrice, Size, SizeRange, Weight, DaysToManufacture, ProductLine, DealerPrice, Class, ModelName, Description, StartDate, EndDate, Status, SubCategory, Category]
Index: []

[0 rows x 21 columns]

In [69]:
products[
    products["StandardCost"].isnull()
]

,ProductKey,ProductSubcategoryKey,ProductName,StandardCost,Color,SafetyStockLevel,ListPrice,Size,SizeRange,Weight,...,ProductLine,DealerPrice,Class,ModelName,Description,StartDate,EndDate,Status,SubCategory,Category
216,210,14,"HL Road Frame - Black, 58",NaN,Black,500,NaN,58,54-58 CM,2.24,...,R,NaN,H,HL Road Frame,Our lightest and best quality aluminum frame m...,1998-06-01,NaT,Current,Road Frames,Components
217,211,14,"HL Road Frame - Red, 58",NaN,Red,500,NaN,58,54-58 CM,2.24,...,R,NaN,H,HL Road Frame,Our lightest and best quality aluminum frame m...,1998-06-01,NaT,Current,Road Frames,Components

In [70]:
products[
    products["ListPrice"].isnull()
]

,ProductKey,ProductSubcategoryKey,ProductName,StandardCost,Color,SafetyStockLevel,ListPrice,Size,SizeRange,Weight,...,ProductLine,DealerPrice,Class,ModelName,Description,StartDate,EndDate,Status,SubCategory,Category
216,210,14,"HL Road Frame - Black, 58",NaN,Black,500,NaN,58,54-58 CM,2.24,...,R,NaN,H,HL Road Frame,Our lightest and best quality aluminum frame m...,1998-06-01,NaT,Current,Road Frames,Components
217,211,14,"HL Road Frame - Red, 58",NaN,Red,500,NaN,58,54-58 CM,2.24,...,R,NaN,H,HL Road Frame,Our lightest and best quality aluminum frame m...,1998-06-01,NaT,Current,Road Frames,Components

In [71]:
products[
    products["DealerPrice"].isnull()
]

,ProductKey,ProductSubcategoryKey,ProductName,StandardCost,Color,SafetyStockLevel,ListPrice,Size,SizeRange,Weight,...,ProductLine,DealerPrice,Class,ModelName,Description,StartDate,EndDate,Status,SubCategory,Category
216,210,14,"HL Road Frame - Black, 58",NaN,Black,500,NaN,58,54-58 CM,2.24,...,R,NaN,H,HL Road Frame,Our lightest and best quality aluminum frame m...,1998-06-01,NaT,Current,Road Frames,Components
217,211,14,"HL Road Frame - Red, 58",NaN,Red,500,NaN,58,54-58 CM,2.24,...,R,NaN,H,HL Road Frame,Our lightest and best quality aluminum frame m...,1998-06-01,NaT,Current,Road Frames,Components

In [72]:
products["Status"].value_counts(dropna=False)

Status
NaN        200
Current    197
Name: count, dtype: int64

In [73]:
products[
    products["ListPrice"] < products["StandardCost"]
]

Empty DataFrame
Columns: [ProductKey, ProductSubcategoryKey, ProductName, StandardCost, Color, SafetyStockLevel, ListPrice, Size, SizeRange, Weight, DaysToManufacture, ProductLine, DealerPrice, Class, ModelName, Description, StartDate, EndDate, Status, SubCategory, Category]
Index: []

[0 rows x 21 columns]

In [74]:
products[
    (products["StandardCost"] < 0) |
    (products["ListPrice"] < 0) |
    (products["DealerPrice"] < 0)
]

Empty DataFrame
Columns: [ProductKey, ProductSubcategoryKey, ProductName, StandardCost, Color, SafetyStockLevel, ListPrice, Size, SizeRange, Weight, DaysToManufacture, ProductLine, DealerPrice, Class, ModelName, Description, StartDate, EndDate, Status, SubCategory, Category]
Index: []

[0 rows x 21 columns]

In [75]:
sales[
    sales["ProductKey"].isin([210, 211])
]

Empty DataFrame
Columns: [ProductKey, OrderDate, OrderDateKey, CustomerKey, SalesTerritoryKey, SalesOrderNumber, SalesOrderLineNumber, OrderQuantity, UnitPrice, ExtendedAmount, UnitPriceDiscountPct, DiscountAmount, ProductStandardCost, TotalProductCost, SalesAmount, TaxAmt, Freight, RegionMonthID]
Index: []

In [76]:
missing_products = products[
    products["StandardCost"].isnull()
]["ProductKey"]

sales[
    sales["ProductKey"].isin(missing_products)
]

Empty DataFrame
Columns: [ProductKey, OrderDate, OrderDateKey, CustomerKey, SalesTerritoryKey, SalesOrderNumber, SalesOrderLineNumber, OrderQuantity, UnitPrice, ExtendedAmount, UnitPriceDiscountPct, DiscountAmount, ProductStandardCost, TotalProductCost, SalesAmount, TaxAmt, Freight, RegionMonthID]
Index: []

In [77]:
products.groupby("ProductName")["ProductKey"].nunique().sort_values(ascending=False)

ProductName
Sport-100 Helmet, Red             3
Sport-100 Helmet, Blue            3
Sport-100 Helmet, Black           3
HL Mountain Frame - Silver, 46    3
HL Mountain Frame - Silver, 42    3
                                 ..
Women's Mountain Shorts, M        1
Women's Mountain Shorts, S        1
Women's Tights, L                 1
Women's Tights, M                 1
Women's Tights, S                 1
Name: ProductKey, Length: 295, dtype: int64

In [78]:
products["ProductSubcategoryKey"].value_counts().sort_index()

ProductSubcategoryKey
1     38
2     65
3     22
4     14
5      3
6      2
7      1
8      3
9      2
10     3
11     3
12    40
13     7
14    70
15     9
16    18
17    14
18     3
19     3
20     9
21    16
22     7
23     4
24     3
25     3
26     1
27     1
28     3
29     1
30     1
31     9
32     1
33     3
34     1
35     1
36     2
37    11
Name: count, dtype: int64

In [79]:
products[
    products["ProductName"] == "Sport-100 Helmet, Red"
][["ProductKey", "StartDate", "EndDate", "Status"]]

     ProductKey  StartDate    EndDate   Status
369         212 2001-07-01 2002-06-30      NaN
370         213 2002-07-01 2003-06-30      NaN
371         214 2003-07-01        NaT  Current

In [80]:
products.dtypes

ProductKey                        int64
ProductSubcategoryKey             int64
ProductName                         str
StandardCost                    float64
Color                               str
SafetyStockLevel                  int64
ListPrice                       float64
Size                                str
SizeRange                           str
Weight                          float64
DaysToManufacture                 int64
ProductLine                         str
DealerPrice                     float64
Class                               str
ModelName                           str
Description                         str
StartDate                datetime64[us]
EndDate                  datetime64[us]
Status                              str
SubCategory                         str
Category                            str
dtype: object

In [81]:
customers = pd.read_excel(excel_file, sheet_name="Customers")

In [82]:
customers.head()

,CustomerKey,GeographyKey,Name,BirthDate,MaritalStatus,Gender,YearlyIncome,NumberChildrenAtHome,Occupation,HouseOwnerFlag,NumberCarsOwned,AddressLine1,AddressLine2,Phone,DateFirstPurchase
0,11602,135,Larry Gill,1977-04-13,S,M,30000,0,Clerical,0,1,Am Gallberg 645,NaN,1 (11) 500 555-0125,2004-01-11
1,11603,244,Geoffrey Gonzalez,1977-02-06,S,M,30000,0,Clerical,0,1,1538 Golden Meadow,NaN,1 (11) 500 555-0131,2002-07-21
2,11610,269,Blake Collins,1975-04-23,S,M,30000,0,Clerical,0,1,4519 Lydia Lane,NaN,1 (11) 500 555-0140,2002-07-13
3,12517,133,Alexa Watson,1977-08-25,S,F,30000,0,Clerical,0,1,Residenz Straße 98,NaN,1 (11) 500 555-0191,2004-04-21
4,12518,161,Jacquelyn Dominguez,1977-09-27,S,F,30000,0,Clerical,0,1,Werftstr 544,NaN,1 (11) 500 555-0134,2004-02-02

In [83]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 20178 entries, 0 to 20177
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CustomerKey           20178 non-null  int64
 1   GeographyKey          20178 non-null  int64
 2   Name                  20178 non-null  str
 3   BirthDate             20178 non-null  datetime64[us]
 4   MaritalStatus         20178 non-null  str
 5   Gender                20178 non-null  str
 6   YearlyIncome          20178 non-null  int64
 7   NumberChildrenAtHome  20178 non-null  int64
 8   Occupation            20178 non-null  str
 9   HouseOwnerFlag        20178 non-null  int64
 10  NumberCarsOwned       20178 non-null  int64
 11  AddressLine1          20178 non-null  str
 12  AddressLine2          312 non-null    str
 13  Phone                 20178 non-null  str
 14  DateFirstPurchase     20178 non-null  datetime64[us]
dtypes: datetime64[us](2), int64(6), str(7)
memory usage: 3.4 MB

In [84]:
customers.isnull().sum()

CustomerKey                 0
GeographyKey                0
Name                        0
BirthDate                   0
MaritalStatus               0
Gender                      0
YearlyIncome                0
NumberChildrenAtHome        0
Occupation                  0
HouseOwnerFlag              0
NumberCarsOwned             0
AddressLine1                0
AddressLine2            19866
Phone                       0
DateFirstPurchase           0
dtype: int64

In [85]:
customers.describe(include='all')

,CustomerKey,GeographyKey,Name,BirthDate,MaritalStatus,Gender,YearlyIncome,NumberChildrenAtHome,Occupation,HouseOwnerFlag,NumberCarsOwned,AddressLine1,AddressLine2,Phone,DateFirstPurchase
count,20178.000000,20178.000000,20178,20178,20178,20178,20178.000000,20178.000000,20178,20178.000000,20178.000000,20178,312,20178,20178
unique,NaN,NaN,18400,NaN,2,2,NaN,NaN,5,NaN,NaN,12797,166,8890,NaN
top,NaN,NaN,Morgan Hall,NaN,M,M,NaN,NaN,Professional,NaN,NaN,Attaché de Presse,Verkaufsabteilung,1 (11) 500 555-0118,NaN
freq,NaN,NaN,4,NaN,10512,10198,NaN,NaN,5961,NaN,NaN,23,34,227,NaN
mean,20245.713896,259.622609,NaN,1963-01-04 17:23:12.685103,NaN,NaN,56190.405392,0.919764,NaN,0.654426,1.484339,NaN,NaN,NaN,2003-08-20 05:17:13.006244
min,11000.000000,2.000000,NaN,1910-08-13 00:00:00,NaN,NaN,10000.000000,0.000000,NaN,0.000000,0.000000,NaN,NaN,NaN,2001-07-01 00:00:00
25%,15637.250000,63.000000,NaN,1955-09-04 00:00:00,NaN,NaN,30000.000000,0.000000,NaN,0.000000,1.000000,NaN,NaN,NaN,2003-04-18 00:00:00
50%,20223.500000,241.000000,NaN,1964-09-26 12:00:00,NaN,NaN,60000.000000,0.000000,NaN,1.000000,1.000000,NaN,NaN,NaN,2003-11-05 00:00:00
75%,24854.750000,347.000000,NaN,1971-11-18 12:00:00,NaN,NaN,70000.000000,1.000000,NaN,1.000000,2.000000,NaN,NaN,NaN,2004-03-13 00:00:00
max,29483.000000,654.000000,NaN,1980-12-26 00:00:00,NaN,NaN,170000.000000,5.000000,NaN,1.000000,4.000000,NaN,NaN,NaN,2004-07-31 00:00:00
std,5332.038117,196.815957,NaN,NaN,NaN,NaN,31836.033917,1.483702,NaN,0.475567,1.109631,NaN,NaN,NaN,NaN

In [86]:
customers.shape

(20178, 15)

In [87]:
customers.dtypes

CustomerKey                      int64
GeographyKey                     int64
Name                               str
BirthDate               datetime64[us]
MaritalStatus                      str
Gender                             str
YearlyIncome                     int64
NumberChildrenAtHome             int64
Occupation                         str
HouseOwnerFlag                   int64
NumberCarsOwned                  int64
AddressLine1                       str
AddressLine2                       str
Phone                              str
DateFirstPurchase       datetime64[us]
dtype: object

In [88]:
customers.duplicated().sum()

np.int64(1694)

In [89]:
customers["CustomerKey"].nunique()

18484

In [90]:
customers["CustomerKey"].duplicated().sum()

np.int64(1694)

In [91]:
sales[~sales["CustomerKey"].isin(customers["CustomerKey"])]

Empty DataFrame
Columns: [ProductKey, OrderDate, OrderDateKey, CustomerKey, SalesTerritoryKey, SalesOrderNumber, SalesOrderLineNumber, OrderQuantity, UnitPrice, ExtendedAmount, UnitPriceDiscountPct, DiscountAmount, ProductStandardCost, TotalProductCost, SalesAmount, TaxAmt, Freight, RegionMonthID]
Index: []

In [92]:
customers[
    customers["CustomerKey"].duplicated(keep=False)
].sort_values("CustomerKey")

,CustomerKey,GeographyKey,Name,BirthDate,MaritalStatus,Gender,YearlyIncome,NumberChildrenAtHome,Occupation,HouseOwnerFlag,NumberCarsOwned,AddressLine1,AddressLine2,Phone,DateFirstPurchase
18922,11003,11,Christy Zhu,1968-02-15,S,F,70000,0,Professional,0,1,1825 Village Pl.,NaN,1 (11) 500 555-0162,2001-07-01
438,11003,11,Christy Zhu,1968-02-15,S,F,70000,0,Professional,0,1,1825 Village Pl.,NaN,1 (11) 500 555-0162,2001-07-01
439,11005,22,Julio Ruiz,1965-08-05,S,M,70000,0,Professional,1,1,7305 Humphrey Drive,NaN,1 (11) 500 555-0151,2001-07-02
18923,11005,22,Julio Ruiz,1965-08-05,S,M,70000,0,Professional,1,1,7305 Humphrey Drive,NaN,1 (11) 500 555-0151,2001-07-02
118,11015,301,Chloe Young,1979-02-27,S,F,30000,0,Skilled Manual,0,1,244 Willow Pass Road,NaN,208-555-0142,2003-07-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,29456,5,Lindsay She,1978-06-27,S,F,10000,0,Manual,1,1,8241 Seawind Dr.,NaN,1 (11) 500 555-0142,2004-03-11
254,29457,33,Cynthia Kapoor,1978-07-28,S,F,10000,0,Manual,0,1,7045 Creekside Drive,NaN,1 (11) 500 555-0180,2004-03-15
18738,29457,33,Cynthia Kapoor,1978-07-28,S,F,10000,0,Manual,0,1,7045 Creekside Drive,NaN,1 (11) 500 555-0180,2004-03-15
20070,29465,8,Roy Gill,1977-06-19,S,M,20000,0,Manual,1,0,4072 South Hampton Road,NaN,1 (11) 500 555-0110,2004-04-22
1586,29465,8,Roy Gill,1977-06-19,S,M,20000,0,Manual,1,0,4072 South Hampton Road,NaN,1 (11) 500 555-0110,2004-04-22

In [93]:
customers.duplicated().sum()

np.int64(1694)

In [94]:
customers.drop_duplicates(inplace=True)

In [95]:
customers.shape
customers.duplicated().sum()
customers["CustomerKey"].nunique()

18484

In [96]:
customers.duplicated().sum()

np.int64(0)

In [97]:
customers["CustomerKey"].nunique()

18484

In [98]:
customers.shape

(18484, 15)

In [99]:
customers["Gender"].value_counts(dropna=False)

Gender
M    9351
F    9133
Name: count, dtype: int64

In [100]:
customers["MaritalStatus"].value_counts(dropna=False)

MaritalStatus
M    10011
S     8473
Name: count, dtype: int64

In [101]:
customers["Occupation"].value_counts()

Occupation
Professional      5520
Skilled Manual    4577
Management        3075
Clerical          2928
Manual            2384
Name: count, dtype: int64

In [102]:
customers["HouseOwnerFlag"].value_counts()

HouseOwnerFlag
1    12502
0     5982
Name: count, dtype: int64

In [103]:
customers["NumberCarsOwned"].value_counts().sort_index()

NumberCarsOwned
0    4238
1    4883
2    6457
3    1645
4    1261
Name: count, dtype: int64

In [104]:
customers[customers["YearlyIncome"]<=0]

Empty DataFrame
Columns: [CustomerKey, GeographyKey, Name, BirthDate, MaritalStatus, Gender, YearlyIncome, NumberChildrenAtHome, Occupation, HouseOwnerFlag, NumberCarsOwned, AddressLine1, AddressLine2, Phone, DateFirstPurchase]
Index: []

In [105]:
customers[customers["DateFirstPurchase"]< customers["BirthDate"]]

Empty DataFrame
Columns: [CustomerKey, GeographyKey, Name, BirthDate, MaritalStatus, Gender, YearlyIncome, NumberChildrenAtHome, Occupation, HouseOwnerFlag, NumberCarsOwned, AddressLine1, AddressLine2, Phone, DateFirstPurchase]
Index: []

In [106]:
customers["AgeAtFirstPurchase"] = (
    customers["DateFirstPurchase"].dt.year -
    customers["BirthDate"].dt.year
)

customers["AgeAtFirstPurchase"].describe()

count    18484.000000
mean        41.549502
std         11.334758
min         21.000000
25%         33.000000
50%         40.000000
75%         49.000000
max         94.000000
Name: AgeAtFirstPurchase, dtype: float64

In [107]:
sales.head()

,ProductKey,OrderDate,OrderDateKey,CustomerKey,SalesTerritoryKey,SalesOrderNumber,SalesOrderLineNumber,OrderQuantity,UnitPrice,ExtendedAmount,UnitPriceDiscountPct,DiscountAmount,ProductStandardCost,TotalProductCost,SalesAmount,TaxAmt,Freight,RegionMonthID
0,528,2003-09-29,20030929,16115,4,SO55161,1,1,4.99,4.99,0,0,1.8663,1.8663,4.99,0.3992,0.1248,Southwest9
1,528,2003-10-01,20031001,15307,4,SO55352,1,1,4.99,4.99,0,0,1.8663,1.8663,4.99,0.3992,0.1248,Southwest10
2,528,2003-10-05,20031005,16003,4,SO55578,1,1,4.99,4.99,0,0,1.8663,1.8663,4.99,0.3992,0.1248,Southwest10
3,528,2003-10-06,20031006,15883,4,SO55635,1,1,4.99,4.99,0,0,1.8663,1.8663,4.99,0.3992,0.1248,Southwest10
4,528,2003-10-08,20031008,15368,4,SO55767,1,1,4.99,4.99,0,0,1.8663,1.8663,4.99,0.3992,0.1248,Southwest10

In [108]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 60398 entries, 0 to 60397
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ProductKey            60398 non-null  int64
 1   OrderDate             60398 non-null  datetime64[us]
 2   OrderDateKey          60398 non-null  int64
 3   CustomerKey           60398 non-null  int64
 4   SalesTerritoryKey     60398 non-null  int64
 5   SalesOrderNumber      60398 non-null  str
 6   SalesOrderLineNumber  60398 non-null  int64
 7   OrderQuantity         60398 non-null  int64
 8   UnitPrice             60398 non-null  float64
 9   ExtendedAmount        60398 non-null  float64
 10  UnitPriceDiscountPct  60398 non-null  int64
 11  DiscountAmount        60398 non-null  int64
 12  ProductStandardCost   60398 non-null  float64
 13  TotalProductCost      60398 non-null  float64
 14  SalesAmount           60398 non-null  float64
 15  TaxAmt                60398 non-null  float64
 16  Freight               60398 non-null  float64
 17  RegionMonthID         60398 non-null  str
dtypes: datetime64[us](1), float64(7), int64(8), str(2)
memory usage: 9.3 MB

In [109]:
sales.describe(include='all')

,ProductKey,OrderDate,OrderDateKey,CustomerKey,SalesTerritoryKey,SalesOrderNumber,SalesOrderLineNumber,OrderQuantity,UnitPrice,ExtendedAmount,UnitPriceDiscountPct,DiscountAmount,ProductStandardCost,TotalProductCost,SalesAmount,TaxAmt,Freight,RegionMonthID
count,60398.000000,60398,6.039800e+04,60398.000000,60398.000000,60398,60398.000000,60398.0,60398.000000,60398.000000,60398.0,60398.0,60398.000000,60398.000000,60398.000000,60398.000000,60398.000000,60398
unique,NaN,NaN,NaN,NaN,NaN,27659,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105
top,NaN,NaN,NaN,NaN,NaN,SO58845,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Australia6
freq,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1359
mean,437.557932,2003-12-11 12:21:38.903937,2.003522e+07,18841.685420,6.244462,NaN,1.886321,1.0,486.086911,486.086911,0.0,0.0,286.065657,286.065657,486.086911,38.886954,12.152217,NaN
min,214.000000,2001-07-01 00:00:00,2.001070e+07,11000.000000,1.000000,NaN,1.000000,1.0,2.290000,2.290000,0.0,0.0,0.856500,0.856500,2.290000,0.183200,0.057300,NaN
25%,359.000000,2003-10-05 00:00:00,2.003100e+07,14003.000000,4.000000,NaN,1.000000,1.0,7.950000,7.950000,0.0,0.0,2.973300,2.973300,7.950000,0.636000,0.198800,NaN
50%,479.000000,2004-01-15 00:00:00,2.004012e+07,18143.000000,7.000000,NaN,2.000000,1.0,29.990000,29.990000,0.0,0.0,11.216300,11.216300,29.990000,2.399200,0.749800,NaN
75%,529.000000,2004-04-20 00:00:00,2.004042e+07,23429.750000,9.000000,NaN,2.000000,1.0,539.990000,539.990000,0.0,0.0,294.579700,294.579700,539.990000,43.199200,13.499800,NaN
max,606.000000,2004-07-31 00:00:00,2.004073e+07,29483.000000,10.000000,NaN,8.000000,1.0,3578.270000,3578.270000,0.0,0.0,2171.294200,2171.294200,3578.270000,286.261600,89.456800,NaN
std,118.088390,NaN,6.394891e+03,5432.430404,2.961150,NaN,1.016328,0.0,928.489892,928.489892,0.0,0.0,552.457641,552.457641,928.489892,74.279193,23.212248,NaN

In [110]:
sales.isnull().sum()

ProductKey              0
OrderDate               0
OrderDateKey            0
CustomerKey             0
SalesTerritoryKey       0
SalesOrderNumber        0
SalesOrderLineNumber    0
OrderQuantity           0
UnitPrice               0
ExtendedAmount          0
UnitPriceDiscountPct    0
DiscountAmount          0
ProductStandardCost     0
TotalProductCost        0
SalesAmount             0
TaxAmt                  0
Freight                 0
RegionMonthID           0
dtype: int64

In [111]:
sales.duplicated().sum()

np.int64(0)

In [112]:
sales.dtypes

ProductKey                       int64
OrderDate               datetime64[us]
OrderDateKey                     int64
CustomerKey                      int64
SalesTerritoryKey                int64
SalesOrderNumber                   str
SalesOrderLineNumber             int64
OrderQuantity                    int64
UnitPrice                      float64
ExtendedAmount                 float64
UnitPriceDiscountPct             int64
DiscountAmount                   int64
ProductStandardCost            float64
TotalProductCost               float64
SalesAmount                    float64
TaxAmt                         float64
Freight                        float64
RegionMonthID                      str
dtype: object

In [113]:
sales.shape

(60398, 18)

In [114]:
sales[~sales["ProductKey"].isin(products["ProductKey"])]

Empty DataFrame
Columns: [ProductKey, OrderDate, OrderDateKey, CustomerKey, SalesTerritoryKey, SalesOrderNumber, SalesOrderLineNumber, OrderQuantity, UnitPrice, ExtendedAmount, UnitPriceDiscountPct, DiscountAmount, ProductStandardCost, TotalProductCost, SalesAmount, TaxAmt, Freight, RegionMonthID]
Index: []

In [115]:
sales[~sales["CustomerKey"].isin(customers["CustomerKey"])]

Empty DataFrame
Columns: [ProductKey, OrderDate, OrderDateKey, CustomerKey, SalesTerritoryKey, SalesOrderNumber, SalesOrderLineNumber, OrderQuantity, UnitPrice, ExtendedAmount, UnitPriceDiscountPct, DiscountAmount, ProductStandardCost, TotalProductCost, SalesAmount, TaxAmt, Freight, RegionMonthID]
Index: []

In [116]:
sales[~sales["SalesTerritoryKey"].isin(territory["Territory Key"])]

Empty DataFrame
Columns: [ProductKey, OrderDate, OrderDateKey, CustomerKey, SalesTerritoryKey, SalesOrderNumber, SalesOrderLineNumber, OrderQuantity, UnitPrice, ExtendedAmount, UnitPriceDiscountPct, DiscountAmount, ProductStandardCost, TotalProductCost, SalesAmount, TaxAmt, Freight, RegionMonthID]
Index: []

In [117]:
sales[~sales["OrderDate"].isin(calendar["Date"])]

Empty DataFrame
Columns: [ProductKey, OrderDate, OrderDateKey, CustomerKey, SalesTerritoryKey, SalesOrderNumber, SalesOrderLineNumber, OrderQuantity, UnitPrice, ExtendedAmount, UnitPriceDiscountPct, DiscountAmount, ProductStandardCost, TotalProductCost, SalesAmount, TaxAmt, Freight, RegionMonthID]
Index: []

In [118]:
sales[
    sales["ExtendedAmount"] !=
    (sales["OrderQuantity"] * sales["UnitPrice"])
]

Empty DataFrame
Columns: [ProductKey, OrderDate, OrderDateKey, CustomerKey, SalesTerritoryKey, SalesOrderNumber, SalesOrderLineNumber, OrderQuantity, UnitPrice, ExtendedAmount, UnitPriceDiscountPct, DiscountAmount, ProductStandardCost, TotalProductCost, SalesAmount, TaxAmt, Freight, RegionMonthID]
Index: []

In [119]:
sales[
    sales["TotalProductCost"] !=
    (
        sales["OrderQuantity"] *
        sales["ProductStandardCost"]
    )
]

Empty DataFrame
Columns: [ProductKey, OrderDate, OrderDateKey, CustomerKey, SalesTerritoryKey, SalesOrderNumber, SalesOrderLineNumber, OrderQuantity, UnitPrice, ExtendedAmount, UnitPriceDiscountPct, DiscountAmount, ProductStandardCost, TotalProductCost, SalesAmount, TaxAmt, Freight, RegionMonthID]
Index: []

In [120]:
sales[
    sales["SalesAmount"] !=
    (
        sales["ExtendedAmount"] -
        sales["DiscountAmount"]
    )
]

Empty DataFrame
Columns: [ProductKey, OrderDate, OrderDateKey, CustomerKey, SalesTerritoryKey, SalesOrderNumber, SalesOrderLineNumber, OrderQuantity, UnitPrice, ExtendedAmount, UnitPriceDiscountPct, DiscountAmount, ProductStandardCost, TotalProductCost, SalesAmount, TaxAmt, Freight, RegionMonthID]
Index: []

In [121]:
sales.duplicated(
    subset=[
        "SalesOrderNumber",
        "SalesOrderLineNumber"
    ]
).sum()

np.int64(0)

In [122]:
sales["GrossProfit"] = (
    sales["SalesAmount"] -
    sales["TotalProductCost"]
)

In [123]:
sales[[
    "SalesAmount",
    "TotalProductCost",
    "GrossProfit"
]].head()

   SalesAmount  TotalProductCost  GrossProfit
0         4.99            1.8663       3.1237
1         4.99            1.8663       3.1237
2         4.99            1.8663       3.1237
3         4.99            1.8663       3.1237
4         4.99            1.8663       3.1237

In [124]:
sales["GrossProfit"].describe()

count    60398.000000
mean       200.021253
std        378.959898
min          1.433500
25%          3.123700
50%         15.643700
75%        196.340400
max       1487.835600
Name: GrossProfit, dtype: float64

In [125]:
(sales["GrossProfit"] < 0).sum()

np.int64(0)

In [126]:
sales["GrossMargin%"] = (
    sales["GrossProfit"] /
    sales["SalesAmount"]
)

In [127]:
sales["GrossMargin%"].describe()

count    60398.000000
mean         0.533516
std          0.136841
min          0.230000
25%          0.394616
50%          0.625992
75%          0.625999
max          0.626001
Name: GrossMargin%, dtype: float64

In [128]:
sales["GrossMargin%"].value_counts().head(10)

GrossMargin%
0.625992    8827
0.625999    6440
0.230000    3926
0.626000    3739
0.625983    3191
0.625990    2376
0.625996    2280
0.626001    2121
0.625996    2025
0.625998    1788
Name: count, dtype: int64

In [130]:
sales["GrossMargin%"].round(6).value_counts().head(10)

GrossMargin%
0.625999    10288
0.625992     8827
0.230000     5522
0.625996     4305
0.626000     4301
0.625998     4262
0.363600     4111
0.454472     3499
0.378400     3199
0.625983     3191
Name: count, dtype: int64

In [131]:
sales.rename(
    columns={"GrossMargin%": "GrossMarginPercent"},
    inplace=True
)

In [132]:
customers[["BirthDate", "DateFirstPurchase"]].dtypes

BirthDate            datetime64[us]
DateFirstPurchase    datetime64[us]
dtype: object

In [133]:
customers["CustomerAge"]=(
    customers["DateFirstPurchase"].dt.year - 
    customers["BirthDate"].dt.year
    )

In [134]:
customers["CustomerAge"].describe()

count    18484.000000
mean        41.549502
std         11.334758
min         21.000000
25%         33.000000
50%         40.000000
75%         49.000000
max         94.000000
Name: CustomerAge, dtype: float64

In [135]:
bins = [18, 25, 35, 45, 55, 100]

labels = [
    "18-25",
    "26-35",
    "36-45",
    "46-55",
    "56+"
]

customers["AgeGroup"] = pd.cut(
    customers["CustomerAge"],
    bins=bins,
    labels=labels,
    include_lowest=True
)

In [136]:
customers["AgeGroup"].value_counts().sort_index()

AgeGroup
18-25     913
26-35    5411
36-45    5932
46-55    3774
56+      2454
Name: count, dtype: int64

In [138]:
customers["YearlyIncome"].describe()

count     18484.000000
mean      57305.777970
std       32285.841703
min       10000.000000
25%       30000.000000
50%       60000.000000
75%       70000.000000
max      170000.000000
Name: YearlyIncome, dtype: float64

In [139]:
bins=[0,30000,70000,float("inf")]
labels=["Low","Medium","High"]
customers["IncomeSegment"]= pd.cut(
customers["YearlyIncome"], bins=bins, labels=labels, include_lowest=True
)

In [140]:
customers["IncomeSegment"].describe()

count      18484
unique         3
top       Medium
freq        8893
Name: IncomeSegment, dtype: object

In [141]:
customers["IncomeSegment"].value_counts()

IncomeSegment
Medium    8893
Low       5209
High      4382
Name: count, dtype: int64

In [142]:
products["ListPrice"].describe()

count     395.000000
mean      747.661762
std       838.708451
min         2.290000
25%        69.990000
50%       364.090000
75%      1204.324800
max      3578.270000
Name: ListPrice, dtype: float64

In [143]:
bins = [0, 69.99, 1204.3248, float("inf")]

labels = [
    "Budget",
    "Mid-Range",
    "Premium"
]

products["PriceSegment"] = pd.cut(
    products["ListPrice"],
    bins=bins,
    labels=labels,
    include_lowest=True
)

In [144]:
products["PriceSegment"].value_counts()

PriceSegment
Mid-Range    197
Budget       100
Premium       98
Name: count, dtype: int64

In [145]:
import os

calendar.to_csv("Data/Clean/DimCalendar.csv", index=False)

territory.to_csv("Data/Clean/DimTerritory.csv", index=False)

categories.to_csv("Data/Clean/DimProductCategory.csv", index=False)

subcategories.to_csv("Data/Clean/DimProductSubcategory.csv", index=False)

products.to_csv("Data/Clean/DimProducts.csv", index=False)

customers.to_csv("Data/Clean/DimCustomers.csv", index=False)

sales.to_csv("Data/Clean/FactSales.csv", index=False)

In [147]:
import os

calendar.to_excel("Data/Clean/DimCalendar.xlsx", index=False)
customers.to_excel("Data/Clean/DimCustomers.xlsx", index=False)
products.to_excel("Data/Clean/DimProducts.xlsx", index=False)
sales.to_excel("Data/Clean/FactSales.xlsx", index=False)
territory.to_excel("Data/Clean/DimTerritory.xlsx", index=False)
categories.to_excel("Data/Clean/DimProductCategory.xlsx", index=False)
subcategories.to_excel("Data/Clean/DimProductSubcategory.xlsx", index=False)